#!/bin/bash
#
# Read and parse lacells configuration
#
# Licensed under GPLv3 or later
# (c)2015 wvengen

# read configuration files from options
config_from_options() {
  local ARGS
  ARGS=$(getopt -q -o C: -l config: -- "$@")
  eval set -- "$ARGS"
  while true; do
    case "$1" in
      -C|--config)
        config_read "$2"
        shift
        ;;
      --)
        break
        ;;
      *)
        shift
        ;;
    esac
  done
}

# read configuration file given
config_read() {
  if [ -r "$1" ]; then
    source "$1"
  else
    echo "WARNING: Cannot read configuration file '$1', skipped." 1>&2
  fi
}

# read configuration file given when it exists
config_try_read() {
  [ -e "$1" ] && config_read "$1"
}

# read default configuration files; give PREFIX as argument
config_default() {
  config_read "$1/misc/creator.cfg"
  config_try_read "${XDG_CONFIG_HOME:-$HOME/.config}/lacells/creator.cfg"
  config_try_read "$1/gen_lacells_conf"
  config_try_read "$1/creator.cfg"
}

